apiVersion: v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  selector:
    matchLables:
      app: myapp
  replicas: 2
  template:
  metadata:
    lables:
      app: myapp
  spec:
    containers:
    - name: myapp
      image: 
      ports:
      - port: 8080
