apiVersion: v1
kind: Deployment
metadata:
  name: myapp
spec:
  selector:
    matchLables:
      app: myapp
  replicas: 2
  template:
    metadata:
      lables:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: nanajanashia/argocd-app:2.0
        ports:
        - port: 8080
